HRMS/Controllers/InterviewMasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRMS.DL.AccountModels;
using HRMS.DL.Entities;
using HRMS.DL.ViewModels;
using Microsoft.AspNet.Identity;
using System.Text;
using System.Net.Mail;
using System.Configuration;
using System.Web.Configuration;
using System.Net.Configuration;

namespace HRMS.Controllers
{
    [Authorize]
    public class InterviewMasterController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: InterviewMaster
        public async Task<ActionResult> Index()
        {
            var tblInterviewMasters = db.tblInterviewMasters.Include(t => t.tblMaInterviewNoticePeriod).Include(t => t.tblMaInterviewResult).Include(t => t.tblMaInterviewTechnology);
            return View(await tblInterviewMasters.OrderByDescending(s=>s.Id).ToListAsync());
        }

        // GET: InterviewMaster/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblInterviewMaster tblInterviewMaster = await db.tblInterviewMasters.FindAsync(id);
            if (tblInterviewMaster == null)
            {
                return HttpNotFound();
            }
            return View(tblInterviewMaster);
        }

        // GET: InterviewMaster/Create
        public ActionResult Create()
        {
            var model = new tblInterviewMasterViewModel();
            ViewBag.NoticePeriod = new SelectList(db.tblMaInterviewNoticePeriods, "Id", "NoticePeriod");
            ViewBag.tblMaInterviewResultId = new SelectList(db.tblMaInterviewResults, "Id", "Status");
            ViewBag.tblMaInterviewTechnologyID = new SelectList(db.tblMaInterviewTechnologies, "Id", "Technology");

            var allUsers = GetUsers();
            ViewBag.InterviewerId = new SelectList(allUsers, "Id", "FirstName");
            ViewBag.tblMaInterviewTypeId = new SelectList(db.tblMaInterviewTypes, "Id", "Type");

            model.AllUsers = allUsers;
            model.AllBranches = db.tblMaCompanyBranch.ToList();

            return View(model);
        }

        public List<ApplicationUser> GetUsers()
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            try
            {
                users = db.Users.ToList();
                users.ForEach(s => s.FirstName = s.FirstName + " " + s.LastName);
                return users;
            }
            catch (Exception)
            {
            }
            return users;
        }

        // POST: InterviewMaster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(tblInterviewMasterViewModel tblInterviewMasterViewModel, HttpPostedFileBase ResumePath)
        {
            try
            {
                //save in master
                var master = new tblInterviewMaster()
                {
                    CurrentCTC = tblInterviewMasterViewModel.CurrentCTC,
                    IsDeleted = false,
                    IsActive = true,
                    CurrentLocation = tblInterviewMasterViewModel.CurrentLocation,
                    ExpectedCTC = tblInterviewMasterViewModel.ExpectedCTC,
                    NoticePeriod = tblInterviewMasterViewModel.NoticePeriod,
                    OtherTechnology = tblInterviewMasterViewModel.OtherTechnology,
                    ResumePath = string.Empty,
                    StudentName = tblInterviewMasterViewModel.StudentName,
                    tblMaInterviewTechnologyID = tblInterviewMasterViewModel.tblMaInterviewTechnologyID,
                    tblMaInterviewResultId = 1,
                    TotalExperience = tblInterviewMasterViewModel.TotalExperience,

                    WhoScheduledId = GetUserId(),
                    ScheduledDateTime= tblInterviewMasterViewModel.ScheduleDateTime.AddDays(-1),
                    EmailId=tblInterviewMasterViewModel.EmailId,
                    PhoneNumber = tblInterviewMasterViewModel.PhoneNumber
                };

                db.tblInterviewMasters.Add(master);
                await db.SaveChangesAsync();

                //update resume path
                string finlePath = string.Empty;
                if (ResumePath != null)
                {
                    string resumePath = Server.MapPath( @"\Content\Resume\");
                    string[] ext = ResumePath.FileName.Split('.');
                    string extt = ext[(ext.Count() - 1)];
                    string fileName = master.StudentName.Replace(" ","_")+ "_Resume_" + master.Id+ "." + extt;
                    finlePath = resumePath + fileName;
                    ResumePath.SaveAs(finlePath);

                    master.ResumePath = @"\Content\Resume\"+ fileName;
                    db.Entry(master).State = EntityState.Modified;
                    db.SaveChanges();
                }

                //save in details
                var details = new tblInterviewDetails()
                {
                    InterviewerId = tblInterviewMasterViewModel.InterviewerId,
                    IsActive = true,
                    IsDeleted = false,
                    IsInterviewTaken = false,
                    ScheduleDateTime = tblInterviewMasterViewModel.ScheduleDateTime,
                    tblInterviewMasterId = master.Id,
                    tblMaInterviewFeedbackStatusId = 4,
                    tblMaInterviewTypeId = tblInterviewMasterViewModel.tblMaInterviewTypeId,
                };
                db.tblInterviewDetails.Add(details);
                await db.SaveChangesAsync();

                //save in notification
                tblMaNotifications notifications = new tblMaNotifications() {
                    Details = "New interview has been scheduled to you by "+GetUserName()+". click here for more details...",
                    DetailsId = details.Id,
                     IsActive=true,
                     IsDeleted=false,
                      IsOpened=false,
                       NotificationType="InterviewScheduled",
                        UserId= tblInterviewMasterViewModel.InterviewerId,
                    SenderName = GetUserName(),
                    DateTime = DateTime.Now
                };
                db.tblMaNotifications.Add(notifications);
                await db.SaveChangesAsync();

                TempData["Y"] = "Interview has been scheduled successfully and Email/Notification has been sent to respective interviewer.";

                //send mail
                var userDetails = db.Users.Where(s=>s.Id== tblInterviewMasterViewModel.InterviewerId).ToList().FirstOrDefault();
                var technolgyDetails = db.tblMaInterviewTechnologies.Where(s=>s.Id== tblInterviewMasterViewModel.tblMaInterviewTechnologyID).FirstOrDefault();
                if (userDetails != null)
                {
                    Appointment appointment = new Appointment();
                    appointment.Name = "Inteview Schedule for " + technolgyDetails.Technology;
                    appointment.Location = "DMI Pune";
                    appointment.Subject = "Inteview Schedule for " + technolgyDetails.Technology;
                    appointment.StartDate = tblInterviewMasterViewModel.ScheduleDateTime;
                    appointment.EndDate = tblInterviewMasterViewModel.ScheduleDateTime.AddHours(2);
                    appointment.Email = "tjagdale@dminc.com";
                    //appointment.Email = userDetails.Email;
                    appointment.Attachment = finlePath;
                    StringBuilder body = new StringBuilder();
                    body.AppendFormat("Hi {0}", userDetails.FirstName);
                    appointment.Body = "Hi " + userDetails.FirstName;

                    sendOutlookInvitationViaICSFile(appointment);
                }
                return RedirectToAction("Create");
            }
            catch (Exception ex)
            {
                ViewBag.NoticePeriod = new SelectList(db.tblMaInterviewNoticePeriods, "Id", "NoticePeriod", tblInterviewMasterViewModel.tblInterviewMaster.NoticePeriod);
                ViewBag.tblMaInterviewResultId = new SelectList(db.tblMaInterviewResults, "Id", "Status", tblInterviewMasterViewModel.tblInterviewMaster.tblMaInterviewResultId);
                ViewBag.tblMaInterviewTechnologyID = new SelectList(db.tblMaInterviewTechnologies, "Id", "Technology", tblInterviewMasterViewModel.tblInterviewMaster.tblMaInterviewTechnologyID);

                ViewBag.InterviewerId = new SelectList(GetUsers(), "Id", "FirstName",tblInterviewMasterViewModel.InterviewerId);
                ViewBag.tblMaInterviewTypeId = new SelectList(db.tblMaInterviewTypes, "Id", "Type",tblInterviewMasterViewModel.tblMaInterviewTypeId);
                TempData["N"] = ex.Message;
                return View(tblInterviewMasterViewModel);
            }
        }

        public string sendOutlookInvitationViaICSFile(Appointment objApptEmail)
        {
            try
            {

                Configuration config = WebConfigurationManager.OpenWebConfiguration(HttpContext.Request.ApplicationPath);
                MailSettingsSectionGroup settings = (MailSettingsSectionGroup)config.GetSectionGroup("system.net/mailSettings");

                SmtpClient sc = new SmtpClient("smtp.gmail.com");

                System.Net.Mail.MailMessage msg = new System.Net.Mail.MailMessage();

                msg.From = new MailAddress(settings.Smtp.Network.UserName);

HRMS/Views/Shared/NavBarTop.cshtml
@using Microsoft.AspNet.Identity
@using HRMS.DL.AccountModels;
@using HRMS.DL.Entities;

@{
    string userName = "Sushmita Roychaudhari";
    string userLocation = "Pune";
    string basePath = HttpContext.Current.Request.Url.ToString().Replace(HttpContext.Current.Request.Url.LocalPath == "/" ? "Ignore" : HttpContext.Current.Request.Url.LocalPath, "");
    string userPic = "/Content/images/SRC.png";
    List<tblMaNotifications> notifications = new List<tblMaNotifications>();
    if (Request.IsAuthenticated)
    {
        userName = User.Identity.GetUserName();

        using (ApplicationDbContext db = new ApplicationDbContext())
        {
            string userId = User.Identity.GetUserId();
            var userData = db.Users.Where(s => s.Id.Equals(userId)).FirstOrDefault();
            if (userData != null)
            {
                userName = string.Format("{0} {1}", userData.FirstName, userData.LastName);
                userPic = userData.ImagePath;
                if (userData.tblMaCompanyBranch != null)
                {
                    userLocation = userData.tblMaCompanyBranch.Location;
                }
            }
            notifications = db.tblMaNotifications.Where(s=>s.UserId==userId).Where(s=>!s.IsOpened).ToList();
        }
    }
    userPic = basePath + userPic;
}

<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav class="" role="navigation">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">

                <li class="pull-left" style="margin:auto;display:block">
                    <p class="pull-left" style="margin:auto;display:block;text-align: center;margin: 0 auto;margin-top: 15px;">
                        DMI HRMS - HUMAR RESOURCE MANAGEMENT SYSTEM  BY
                        @*<span class="lead">
                Lazy Ninja
            </span>*@
                    </p>
                    &nbsp;&nbsp;&nbsp; <img height="50" width="150" src="~/Content/images/LazyNinja_logo_new_512.png" />
                </li>

                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="@userPic" alt="">@userName
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                        @*<li>
                                <a href="javascript:;">  Profile</a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <span class="badge bg-red pull-right">50%</span>
                                    <span>Settings</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">Help</a>
                            </li>*@

                        <li>
                            @if (Request.IsAuthenticated)
                            {
                                <a href="~/Account/LogOff"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                            }
                            else
                            {
                                <a href="~/Account/Login">Log in</a>
                            }
                        </li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">@notifications.Count()</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
                        @foreach (var item in notifications.Take(3))
                                    {
                                        var result = (DateTime.Now - item.DateTime);
                                        string duration = "";

                                        double durationInDay = Convert.ToInt64( result.TotalDays);
                                        duration = durationInDay.ToString() + " days ago" ;
                                        if (durationInDay <= 0)
                                        {
                                            double durationInHr = Convert.ToInt64(result.TotalHours);
                                            duration = durationInHr.ToString() + " hours ago";
                                            if (durationInHr <= 0)
                                            {
                                                double durationInMin = Convert.ToInt64(result.TotalMinutes);
                                                duration = durationInMin.ToString() + " minutes ago";
                                                if (durationInMin <= 0)
                                                {
                                                    double durationInSec = Convert.ToInt64(result.TotalSeconds);
                                                    duration = durationInSec.ToString() + " seconds ago";
                                                }
                                            }
                                        }

                             <li>
                            <a href="@Url.Action("SubmitFeedback","InterviewMaster")" >
                                <span class="image">
                                    <img src="@userPic" alt="Profile Image" />
                                </span>
                                <span>
                                    <span>@item.SenderName</span>
                                    <span class="time">@duration</span>
                                </span>
                                <span class="message">
                                   @item.Details
                                </span>
                            </a>
                        </li>
                        }
                            @if (notifications.Count == 0)
                            {
                            <li>
                            <a>
                                <span class="image">
                                    <img src="@userPic" alt="Profile Image" />
                                </span>
                                <span>
                                    <span>@userName</span> 
                                </span>
                                <span class="message">
                                   You dont have any notification
                                </span>
                            </a>
                        </li>
                        }
                        @if (notifications.Count > 3)
                        {
                            <li>
                            <div class="text-center">
                                <a>
                                    <strong><a href="@Url.Action("SubmitFeedback","InterviewMaster")">See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                        }

                        @*<li>
                            <a>
                                <span class="image">
                                    <img src="~/Content/images/img.jpg" alt="Profile Image" />
                                </span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image">
                                    <img src="~/Content/images/img.jpg" alt="Profile Image" />
                                </span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image">
                                    <img src="~/Content/images/img.jpg" alt="Profile Image" />
                                </span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong><a href="inbox.html">See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>*@
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

HRMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DMI HRMS</title>
    @*<link href="~/Content/css/bootstrap.min.css" rel="stylesheet">*@

</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            @Html.Partial("NavBarLeft")
            @Html.Partial("NavBarTop")
            @RenderBody()
        </div>
    </div>
    <div id="custom_notifications" class="custom-notifications dsp_none">
        <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group"></ul>
        <div class="clearfix"></div>
        <div id="notif-group" class="tabbed_notifications"></div>
    </div>
</body>
</html>

HRMS/Views/Shared/_StatusMessage.cshtml
@{
    string success = TempData["Y"] == null ?"": TempData["Y"].ToString();
    string danger = TempData["N"] == null ? "" : TempData["N"].ToString();
    string warning = TempData["W"] == null ? "" : TempData["W"].ToString(); 
}
<div class="x_content bs-example-popovers">
    @if (!string.IsNullOrEmpty(success))
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <strong>Success:</strong> @success
        </div>
    }

    @if (!string.IsNullOrEmpty(warning))
    {
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <strong>Warning:</strong> @warning
        </div>
    }

    @if (!string.IsNullOrEmpty(danger))
    {
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <strong>Error:</strong> @danger
        </div>
    }




</div>